-- SQL Migration: Create public.halaman_statis table and initialize default data
-- Execute this query in the Supabase SQL Editor:

-- 1. Create table
CREATE TABLE IF NOT EXISTS public.halaman_statis (
    slug VARCHAR(50) PRIMARY KEY,
    judul VARCHAR(100) NOT NULL,
    konten TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Insert initial rows for the 4 static pages
INSERT INTO public.halaman_statis (slug, judul, konten) VALUES
('tentang-kami', 'Tentang Kami', '<p><strong>PojokTV.com</strong> adalah portal berita digital mutakhir yang lahir dari komitmen untuk menyajikan jurnalisme yang independen, akurat, dan berimbang. Kami hadir di tengah derasnya arus informasi untuk menjadi jangkar kebenaran bagi masyarakat Indonesia.</p><p>Mengusung visi <em>“Mencerahkan dan Mencerdaskan”</em>, redaksi PojokTV bekerja dengan mengedepankan etika jurnalistik yang ketat. Kami menyajikan berbagai rubrik komprehensif mulai dari Pemerintahan, Ekonomi, Hukum, hingga ragam Peristiwa hangat yang terjadi di seluruh penjuru nusantara.</p><p>Didukung oleh tim editorial yang berpengalaman dan sistem teknologi informasi terkini, PojokTV memastikan setiap berita yang sampai ke layar Anda telah melalui proses verifikasi fakta yang ketat, menjamin kecepatan tanpa mengorbankan akurasi.</p>'),

('pedoman-media', 'Pedoman Pemberitaan Media Siber', '<p>Kemerdekaan berpendapat, kemerdekaan berekspresi, dan kemerdekaan pers adalah hak asasi manusia yang dilindungi Pancasila, Undang-Undang Dasar 1945, dan Deklarasi Universal Hak Asasi Manusia PBB. Keberadaan media siber di Indonesia juga merupakan bagian dari kemerdekaan berpendapat dan berekspresi.</p><p>Oleh karena itu, <strong>PojokTV.com</strong> secara penuh tunduk dan patuh pada Pedoman Pemberitaan Media Siber yang ditetapkan oleh Dewan Pers.</p><div class="border-l-4 border-red-500 pl-5 space-y-5"><div><h2 class="font-bold text-slate-900 text-lg mb-1">Verifikasi dan Keberimbangan</h2><p>Setiap berita harus melalui verifikasi. Berita yang merugikan pihak lain menuntut verifikasi pada berita yang sama untuk memenuhi prinsip akurasi dan keberimbangan.</p></div><div><h2 class="font-bold text-slate-900 text-lg mb-1">Ralat, Koreksi, dan Hak Jawab</h2><p>Ralat, koreksi, dan hak jawab mengacu pada Undang-Undang Pers, Kode Etik Jurnalistik, dan Pedoman Hak Jawab yang ditetapkan Dewan Pers.</p></div><div><h2 class="font-bold text-slate-900 text-lg mb-1">Pencabutan Berita</h2><p>Berita yang sudah dipublikasikan tidak dapat dicabut karena alasan penyensoran dari pihak luar redaksi, kecuali terkait masalah SARA, kesusilaan, masa depan anak, pengalaman traumatik korban, atau pertimbangan khusus lain yang ditetapkan Dewan Pers.</p></div></div>'),

('kebijakan-privasi', 'Kebijakan Privasi', '<p><strong>PojokTV.com</strong> menghargai privasi Anda dan berkomitmen untuk melindungi data pribadi pengguna. Kebijakan ini menjelaskan bagaimana kami mengumpulkan, menggunakan, dan melindungi informasi Anda saat mengakses layanan kami.</p><div class="border-l-4 border-red-500 pl-5 space-y-5"><div><h2 class="font-bold text-slate-900 text-lg mb-1">Pengumpulan Data</h2><p>Kami secara otomatis mengumpulkan informasi teknis non-pribadi seperti alamat IP, jenis peramban, dan data analitik kunjungan melalui teknologi cookies guna meningkatkan pengalaman pengguna (UI/UX) dan relevansi konten.</p></div><div><h2 class="font-bold text-slate-900 text-lg mb-1">Penggunaan Informasi</h2><p>Data yang dikumpulkan digunakan secara internal oleh PojokTV untuk keperluan analisis trafik, optimasi server, dan pengembangan layanan. Kami tidak akan menjual, menyewakan, atau mendistribusikan data pribadi Anda kepada pihak ketiga tanpa izin eksplisit dari Anda, kecuali diwajibkan oleh hukum dan peraturan perundang-undangan di Republik Indonesia.</p></div></div>'),

('ketentuan-layanan', 'Ketentuan Layanan', '<p>Selamat datang di <strong>PojokTV.com</strong>. Dengan mengakses dan menggunakan situs ini, Anda secara otomatis menyetujui Ketentuan Layanan berikut:</p><div class="border-l-4 border-red-500 pl-5 space-y-5"><div><h2 class="font-bold text-slate-900 text-lg mb-1">Hak Cipta Konten</h2><p>Seluruh materi konten (teks, foto, video, logo, dan infografis) di PojokTV.com dilindungi oleh Undang-Undang Hak Cipta. Penggunaan, penyalinan, atau reproduksi konten untuk tujuan komersial tanpa izin tertulis dari redaksi adalah pelanggaran hukum.</p></div><div><h2 class="font-bold text-slate-900 text-lg mb-1">Kutipan Berita</h2><p>Penggunaan konten PojokTV untuk keperluan referensi atau pendidikan diperbolehkan dengan syarat mutlak mencantumkan tautan (link) aktif yang mengarah langsung ke halaman sumber di PojokTV.com.</p></div><div><h2 class="font-bold text-slate-900 text-lg mb-1">Tanggung Jawab Pengguna</h2><p>Pengguna dilarang menggunakan situs ini untuk tindakan yang melanggar hukum, menyebarkan hoaks, ujaran kebencian, atau merusak sistem keamanan server (hacking/spamming).</p></div></div>')
ON CONFLICT (slug) DO UPDATE 
SET judul = EXCLUDED.judul, konten = EXCLUDED.konten;
